# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162eL4AKQzp8sa12y0wkDGypUvmRSOwKG
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load cleaned data
cleaned_data_path = '/content/sample_data/student/data_clean/cleaned_student_performance.csv'
df = pd.read_csv(cleaned_data_path)

# Set seaborn style for consistent visualizations
sns.set(style="whitegrid")

# 1. Parental Education vs Student Performance (Bar Plot)
plt.figure(figsize=(10, 6))
sns.barplot(x='parental_education', y='math_score', data=df, palette='Set2')
plt.title('Parental Education vs Math Score')
plt.xlabel('Parental Level of Education')
plt.ylabel('Average Math Score')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('/content/sample_data/student/results/parental_education_vs_math.png')
plt.show()

# 2. Test Preparation Course vs Student Performance (Box Plot)
plt.figure(figsize=(10, 6))
sns.boxplot(x='test preparation course', y='math_score', data=df, palette='coolwarm')
plt.title('Test Preparation Course vs Math Score')
plt.xlabel('Test Preparation Course')
plt.ylabel('Math Score')
plt.tight_layout()
plt.savefig('/content/sample_data/student/results/test_prep_vs_math.png')
plt.show()

# 3. Lunch Type vs Student Performance (Violin Plot)
plt.figure(figsize=(10, 6))
sns.violinplot(x='lunch', y='math_score', data=df, palette='muted')
plt.title('Lunch Type vs Math Score')
plt.xlabel('Lunch Type')
plt.ylabel('Math Score')
plt.tight_layout()
plt.savefig('/content/sample_data/student/results/lunch_vs_math.png')
plt.show()

# 4. Gender vs Student Performance (Grouped Bar Plot)
plt.figure(figsize=(10, 6))
df.groupby('gender')[['math_score', 'reading_score', 'writing_score']].mean().plot(kind='bar', figsize=(10, 6), color=['skyblue', 'orange', 'green'])
plt.title('Gender vs Average Scores in Math, Reading, and Writing')
plt.xlabel('Gender')
plt.ylabel('Average Score')
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig('/content/sample_data/student/results/gender_vs_scores.png')
plt.show()

# 5. Correlation Between Math, Reading, and Writing Scores (Heatmap)
plt.figure(figsize=(8, 6))
corr_matrix = df[['math_score', 'reading_score', 'writing_score']].corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', vmin=-1, vmax=1)
plt.title('Correlation Between Math, Reading, and Writing Scores')
plt.tight_layout()
plt.savefig('/content/sample_data/student/results/score_correlation_heatmap.png')
plt.show()